server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: UserServiceRoute
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: UserServiceBreaker
                fallbackUri: forward:/fallback/user

        - id: NotificationServiceRoute
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/notifications/**
          filters:
            - name: CircuitBreaker
              args:
                name: NotificationBreaker
                fallbackUri: forward:/fallback/notification

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
