server:
  port: 8082

spring:
  application:
    name: notification-service

  mail:
    host: localhost
    port: 1025
    username:
    password:
    from: noreply@user-service.com
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false


  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ${spring.application.name}
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.value.default.type: aston.homework.notification.event.UserEvent
        spring.json.use.type.headers: false

app:
  kafka:
    topic:
      user-events: user-events

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
